-- The Season XII semifinal batting lines, from the same source as 0077.
--
-- Batting was in better shape than the pitching was: 132 of the 147 lines
-- already matched MyStatsOnline exactly. Fifteen did not, and eleven batters
-- had no row here at all - DaMineyCraftKen in 4028, AbusiveStepdad66 in 4029,
-- and others across 4033, 4034 and 4036. Nothing we held was absent from the
-- source, so replacing the set loses no one.
--
-- The same checks as 0077, and two more that only batting allows:
--
--   * Every one of the sixteen blocks adds up to its own TOTAL row, and the
--     hits split adds up too - singles, doubles, triples and home runs come to
--     the hit total on all sixteen.
--   * Each side's runs equal its own final score from the schedule page.
--   * Each side's hits and errors equal its own line score. That last one is
--     what decides the error column: MyStatsOnline agrees with the line score
--     on all sixteen sides and the hand-counted figures disagree on three, so
--     errors are taken from the source throughout.
--
-- Hit by pitch and sacrifice bunts are written as nought rather than left
-- empty, and that is a measurement, not an assumption: plate appearances less
-- at-bats, walks and sacrifice flies comes to nought for all 147 batters, and
-- those two are the only things left that it could have been. Round one
-- carries both columns; the semifinals carried neither, nor sacrifice flies,
-- nor left on base. All four are filled in now.
--
-- Putouts are the one column the source is short on, so they are the one thing
-- not taken from it wholesale. A side's putouts should equal the outs its own
-- pitchers recorded, and MyStatsOnline's do on nine of the sixteen sides and
-- fall short on six - on 4032's home side it records none at all against
-- twenty-one outs. So the nine take the source's figures and the six keep the
-- hand-counted ones already here, which are never more than the outs either.
-- A batter the hand count never saw keeps a null rather than a nought, because
-- what he did is unknown and nought is a claim. 331 of the 340 putouts are
-- accounted for, and no side is credited with more than it made - which a
-- per-player merge of the two sources did produce, giving 4029's home side
-- twenty putouts in an eighteen-out game.
--
-- position_outs stays empty, as it already is. MyStatsOnline records what a
-- man did, not where he stood.

DELETE FROM historical_game_stats WHERE kind = 'BATTING' AND game_id IN (4027,4028,4029,4032,4033,4034,4035,4036);

-- 4027: Grizzlies 2-8 Panthers  [MyStatsOnline game 1960746]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'Hibitt', 3, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'TeamminNoodle', 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'Casfection', 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'luxor1967', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'Adurice', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'kwot', 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'Pureleqf', 3, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'forte47252', 3, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, NULL, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'LBBroadway', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 0, 'BATTING', 'ysba', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'Joshygg', 4, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'Girty', 4, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 2);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', '_littL_', 2, 2, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'peejamillion', 3, 2, 2, 0, 0, 1, 3, 0, 0, 0, 1, 0, 0, 0, 0, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'dcjenk22', 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'Rebtsuna', 3, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'NoScopeMason1', 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', 'EthanS22', 3, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4027, 1, 'BATTING', '_TheNoah_', 3, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0);

-- 4028: Panthers 9-8 Grizzlies  [MyStatsOnline game 1960747]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'Joshygg', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', '_littL_', 2, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'Girty', 4, 4, 4, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'peejamillion', 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 9, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'dcjenk22', 4, 1, 1, 0, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'Rebtsuna', 3, 1, 2, 0, 0, 1, 3, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'NoScopeMason1', 4, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'EthanS22', 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'KexKK', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 0, 'BATTING', 'DaMineyCraftKen', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'Hibitt', 3, 2, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'luxor1967', 4, 2, 3, 1, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'Casfection', 3, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'Vision', 4, 1, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'kwot', 3, 1, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 3, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'TeamminNoodle', 3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'BANKKID', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'Pureleqf', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'LBBroadway', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4028, 1, 'BATTING', 'forte47252', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

-- 4029: Grizzlies 2-5 Panthers  [MyStatsOnline game 1960748]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'Hibitt', 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'luxor1967', 3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'Casfection', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'Vision', 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'Adurice', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'TeamminNoodle', 3, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'BANKKID', 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'Pureleqf', 2, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'HyperB_', 3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 0, 'BATTING', 'AbusiveStepdad66', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'Girty', 2, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', '_littL_', 3, 1, 1, 0, 0, 1, 3, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'peejamillion', 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 7, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'dcjenk22', 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'Rebtsuna', 3, 0, 2, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'KexKK', 3, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 2, 2, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'EthanS22', 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4029, 1, 'BATTING', 'DaMineyCraftKen', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);

-- 4032: Otters 0-2 Expos (7th)  [MyStatsOnline game 1960751]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'omgitsgabee', 3, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'pumkinnzzz', 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'Weers', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'bmodep6', 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'xx6tttsahur7xx', 3, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'AarBear426', 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 4, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'pogJ', 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 9, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'dr1pkid', 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'IcedFlxme', 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 0, 'BATTING', 'LargeMines267', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'Drypho', 4, 1, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'Titansstorm1', 3, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'NuttyMcNutt', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 13, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'WiiillG', 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'Sec6et', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'IcedNerd', 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'Lachy_Balboa', 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'ratedjr', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4032, 1, 'BATTING', 'TheSeethanMan69', 3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);

-- 4033: Expos 0-3 Otters (13th)  [MyStatsOnline game 1960752]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'Drypho', 5, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 5, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'Titansstorm1', 5, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'NuttyMcNutt', 5, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 20, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'WiiillG', 4, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'TheSeethanMan69', 5, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 4, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'ratedjr', 5, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 1, 5, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'IcedNerd', 5, 0, 1, 0, 0, 0, 0, 0, 4, 0, 2, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'CarrotGodJeff', 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'Binbit', 4, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'Herwes', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 0, 'BATTING', 'Lachy_Balboa', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'omgitsgabee', 6, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'SonicBoss101', 4, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 7, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'bmodep6', 6, 1, 2, 0, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'xx6tttsahur7xx', 5, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 11, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'TropicaljjXx', 5, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 13, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'dr1pkid', 4, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'IcedFlxme', 5, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'Pro_Gamer4957', 5, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4033, 1, 'BATTING', 'pogJ', 5, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0);

-- 4034: Otters 2-0 Expos (8th)  [MyStatsOnline game 1960753]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'omgitsgabee', 4, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'pumkinnzzz', 4, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'xx6tttsahur7xx', 3, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'bmodep6', 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'pogJ', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'SonicBoss101', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'AarBear426', 3, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'TropicaljjXx', 3, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 10, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 0, 'BATTING', 'IcedFlxme', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'Drypho', 4, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'Titansstorm1', 4, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'Lachy_Balboa', 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'WiiillG', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'NuttyMcNutt', 3, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 11, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'TheSeethanMan69', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'ratedjr', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'IcedNerd', 3, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'Binbit', 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 7, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4034, 1, 'BATTING', 'CarrotGodJeff', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

-- 4035: Expos 3-0 Otters  [MyStatsOnline game 1960754]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'Drypho', 3, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'Titansstorm1', 3, 1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'NuttyMcNutt', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'WiiillG', 3, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'Lachy_Balboa', 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'ratedjr', 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'Pichipah', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'Binbit', 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 0, 'BATTING', 'CarrotGodJeff', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'Weers', 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'omgitsgabee', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'xx6tttsahur7xx', 3, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'TropicaljjXx', 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 3, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'Donkeymario65', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'SonicBoss101', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'AarBear426', 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'IcedFlxme', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'pogJ', 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 10, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4035, 1, 'BATTING', 'dr1pkid', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0);

-- 4036: Otters 3-2 Expos  [MyStatsOnline game 1960755]
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'Weers', 3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'pumkinnzzz', 3, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'bmodep6', 3, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'xx6tttsahur7xx', 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'AarBear426', 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'omgitsgabee', 3, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'SonicBoss101', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'Donkeymario65', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 8, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'pogJ', 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'Pro_Gamer4957', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'IcedFlxme', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 0, 'BATTING', 'dr1pkid', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'Drypho', 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'Titansstorm1', 2, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'NuttyMcNutt', 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 1);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'WiiillG', 3, 1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'Binbit', 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'IcedNerd', 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'Lachy_Balboa', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'TheSeethanMan69', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'ratedjr', 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'Herwes', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'Pichipah', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO historical_game_stats (game_id, is_home, kind, player_name, at_bats, runs, hits, doubles, triples, home_runs, rbis, walks, strikeouts, hit_by_pitch, stolen_bases, caught_stealing, sac_flies, sac_bunts, left_on_base, putouts, errors) VALUES (4036, 1, 'BATTING', 'CarrotGodJeff', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0);

